# -*- coding: utf-8 -*-
"""Task 3: Energy Consumption Time Series Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1my06nj4aqSmcMAnyajDl9ZnHZvj2hZiV
"""

# CELL 1 – Install dependencies
import subprocess, sys

def pip(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

for pkg in ["prophet", "statsmodels", "xgboost", "scikit-learn"]:
    pip(pkg)

print("✅  All packages ready.")

# CELL 2 – Imports

import warnings, os, zipfile, urllib.request
warnings.filterwarnings("ignore")

import numpy             as np
import pandas            as pd
import matplotlib.pyplot as plt
import matplotlib.dates  as mdates

# ── Colab-specific: render plots inline in the notebook output ──
try:
    from IPython import get_ipython
    get_ipython().run_line_magic("matplotlib", "inline")
    import matplotlib
    matplotlib.rcParams["figure.dpi"] = 110          # crisp Colab display
    IN_COLAB = True
except Exception:
    IN_COLAB = False                                  # plain .py fallback

from sklearn.metrics              import mean_absolute_error, mean_squared_error
from statsmodels.tsa.arima.model  import ARIMA
from prophet                      import Prophet
from xgboost                      import XGBRegressor

print("✅  Imports complete.")

# CELL 3 – Download & parse the UCI dataset
DATA_URL = ("https://archive.ics.uci.edu/ml/machine-learning-databases/"
            "00235/household_power_consumption.zip")
ZIP_PATH = "household_power_consumption.zip"
CSV_PATH = "household_power_consumption.txt"

if not os.path.exists(CSV_PATH):
    print("⬇  Downloading dataset (~20 MB) …")
    urllib.request.urlretrieve(DATA_URL, ZIP_PATH)
    with zipfile.ZipFile(ZIP_PATH) as z:
        z.extractall(".")
    print("✅  Download complete.")
else:
    print("✅  Dataset already on disk.")

print("📂  Parsing …")
df = pd.read_csv(
    CSV_PATH, sep=";",
    parse_dates={"Datetime": ["Date", "Time"]},
    dayfirst=True, na_values=["?"], low_memory=False,
)
df = df.sort_values("Datetime").set_index("Datetime")
df["Global_active_power"] = pd.to_numeric(df["Global_active_power"], errors="coerce")
df = df[["Global_active_power"]].dropna()

# ── Resample 1-min → hourly mean ──
df_hourly = df.resample("H").mean().dropna()
print(f"✅  {len(df_hourly):,} hourly records  "
      f"({df_hourly.index.min().date()} → {df_hourly.index.max().date()})")


# CELL 4 – Time-based feature engineering
def add_time_features(data: pd.DataFrame) -> pd.DataFrame:
    d = data.copy()
    # Calendar primitives
    d["hour"]       = d.index.hour
    d["dayofweek"]  = d.index.dayofweek
    d["month"]      = d.index.month
    d["dayofyear"]  = d.index.dayofyear
    d["is_weekend"] = (d.index.dayofweek >= 5).astype(int)
    # Cyclical encodings (prevent artificial discontinuities)
    d["hour_sin"]   = np.sin(2 * np.pi * d["hour"]     / 24)
    d["hour_cos"]   = np.cos(2 * np.pi * d["hour"]     / 24)
    d["dow_sin"]    = np.sin(2 * np.pi * d["dayofweek"]/ 7)
    d["dow_cos"]    = np.cos(2 * np.pi * d["dayofweek"]/ 7)
    d["month_sin"]  = np.sin(2 * np.pi * d["month"]    / 12)
    d["month_cos"]  = np.cos(2 * np.pi * d["month"]    / 12)
    # Lag features (XGBoost)
    for lag in [1, 2, 3, 24, 48, 168]:
        d[f"lag_{lag}"] = d["Global_active_power"].shift(lag)
    # Rolling statistics
    for w in [6, 24, 168]:
        d[f"rolling_mean_{w}"] = d["Global_active_power"].shift(1).rolling(w).mean()
        d[f"rolling_std_{w}"]  = d["Global_active_power"].shift(1).rolling(w).std()
    return d

df_feat = add_time_features(df_hourly)
print("✅  Features engineered:", list(df_feat.columns))

# CELL 5 – Train / test split  (last 7 days as test set)
TEST_HOURS  = 7 * 24          # 168 hours
WINDOW_DAYS = 180             # use last 6 months to keep training fast

df_window = df_feat.iloc[-(WINDOW_DAYS * 24 + TEST_HOURS):]
train     = df_window.iloc[:-TEST_HOURS]
test      = df_window.iloc[-TEST_HOURS:]

y_train = train["Global_active_power"]
y_test  = test["Global_active_power"]

print(f"✅  Train: {len(train):,} h  |  Test: {len(test):,} h  "
      f"({test.index.min().date()} → {test.index.max().date()})")


# CELL 6 – Evaluation helper
def evaluate(name, actual, predicted):
    actual    = actual.reindex(predicted.index).dropna()
    predicted = predicted.reindex(actual.index).dropna()
    mae  = mean_absolute_error(actual, predicted)
    rmse = np.sqrt(mean_squared_error(actual, predicted))
    mape = np.mean(np.abs((actual - predicted) / actual.replace(0, np.nan))) * 100
    print(f"  {name:<10}  MAE={mae:.4f}  RMSE={rmse:.4f}  MAPE={mape:.2f}%")
    return {"Model": name, "MAE": mae, "RMSE": rmse, "MAPE": mape}


# CELL 7 – ARIMA
print("\n[1/3]  Fitting ARIMA(2,1,2) on last 30 days …")
arima_train = y_train.iloc[-30 * 24:]
arima_fit   = ARIMA(arima_train, order=(2, 1, 2)).fit()
arima_pred  = pd.Series(
    arima_fit.forecast(steps=TEST_HOURS).values,
    index=y_test.index,
)
metrics_arima = evaluate("ARIMA", y_test, arima_pred)

# CELL 8 – Prophet
print("\n[2/3]  Fitting Prophet …")
prophet_df = train[["Global_active_power"]].reset_index()
prophet_df.columns = ["ds", "y"]

m_prophet = Prophet(
    daily_seasonality       = True,
    weekly_seasonality      = True,
    yearly_seasonality      = False,
    changepoint_prior_scale = 0.05,
)
m_prophet.fit(prophet_df)

future       = m_prophet.make_future_dataframe(periods=TEST_HOURS, freq="H")
fcst         = m_prophet.predict(future)
prophet_pred = fcst.set_index("ds")["yhat"].loc[y_test.index]
metrics_prophet = evaluate("Prophet", y_test, prophet_pred)


# CELL 9 – XGBoost
print("\n[3/3]  Fitting XGBoost …")
feature_cols = [c for c in df_feat.columns if c != "Global_active_power"]

train_xgb   = train[feature_cols + ["Global_active_power"]].dropna()
test_xgb    = test[feature_cols  + ["Global_active_power"]].dropna()

X_tr, y_tr  = train_xgb[feature_cols], train_xgb["Global_active_power"]
X_te, y_te  = test_xgb[feature_cols],  test_xgb["Global_active_power"]

xgb_model = XGBRegressor(
    n_estimators=500, learning_rate=0.05, max_depth=6,
    subsample=0.8, colsample_bytree=0.8, random_state=42, n_jobs=-1,
)
xgb_model.fit(X_tr, y_tr, eval_set=[(X_te, y_te)], verbose=False)
xgb_pred      = pd.Series(xgb_model.predict(X_te), index=y_te.index)
metrics_xgb   = evaluate("XGBoost", y_te, xgb_pred)

# CELL 10 – Helper: show_or_save  (inline in Colab, PNG on disk)
def show_or_save(filename: str):
    """Display inline in Colab; also always saves a PNG."""
    plt.savefig(filename, dpi=130, bbox_inches="tight")
    plt.show()          # renders inline in Colab notebook output
    plt.close()
    print(f"  💾  {filename}")

# CELL 11 – Plot 1: Forecast Comparison (4-panel)
COLORS = {
    "Actual" : "#2c3e50",
    "ARIMA"  : "#e74c3c",
    "Prophet": "#2980b9",
    "XGBoost": "#27ae60",
}
common_idx = y_test.index
all_metrics = [metrics_arima, metrics_prophet, metrics_xgb]
preds       = {
    "ARIMA"  : arima_pred.reindex(common_idx),
    "Prophet": prophet_pred.reindex(common_idx),
    "XGBoost": xgb_pred.reindex(common_idx),
}

fig, axes = plt.subplots(4, 1, figsize=(16, 22), sharex=False)
fig.suptitle(
    "Household Energy Consumption – Forecast Comparison\n(7-day test window)",
    fontsize=15, fontweight="bold", y=0.995,
)

# Panel 0 – historical overview
ax0 = axes[0]
overview = df_hourly.iloc[-30 * 24 - TEST_HOURS:]
ax0.plot(overview.index, overview["Global_active_power"],
         color=COLORS["Actual"], lw=0.8, alpha=0.7, label="Historical")
ax0.axvspan(common_idx[0], common_idx[-1], alpha=0.12,
            color="orange", label="Forecast window")
ax0.set_title("Overview – Last 30 days + 7-day forecast window", fontsize=11)
ax0.set_ylabel("Power (kW)")
ax0.legend(loc="upper left", fontsize=9)
ax0.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
ax0.xaxis.set_major_locator(mdates.WeekdayLocator(interval=1))
ax0.grid(alpha=0.3)

# Panels 1-3 – each model vs actual
for ax, name in zip(axes[1:], ["ARIMA", "Prophet", "XGBoost"]):
    m    = next(x for x in all_metrics if x["Model"] == name)
    pred = preds[name]

    ax.plot(common_idx, y_test.reindex(common_idx),
            color=COLORS["Actual"], lw=1.8, label="Actual", zorder=3)
    ax.plot(pred.index, pred.values,
            color=COLORS[name], lw=1.8, ls="--",
            label=f"{name} Forecast", zorder=2)
    ax.fill_between(
        common_idx,
        y_test.reindex(common_idx), pred,
        alpha=0.15, color=COLORS[name],
    )
    ax.set_title(
        f"{name}  │  MAE={m['MAE']:.4f}  RMSE={m['RMSE']:.4f}  MAPE={m['MAPE']:.2f}%",
        fontsize=11,
    )
    ax.set_ylabel("Power (kW)")
    ax.legend(loc="upper left", fontsize=9)
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
    ax.xaxis.set_major_locator(mdates.DayLocator(interval=1))
    ax.grid(alpha=0.3)

fig.autofmt_xdate(rotation=30, ha="right")
plt.tight_layout(rect=[0, 0, 1, 0.995])
show_or_save("forecast_comparison.png")

# CELL 12 – Plot 2: Metrics bar chart
metrics_df  = pd.DataFrame(all_metrics).set_index("Model")
bar_colors  = [COLORS["ARIMA"], COLORS["Prophet"], COLORS["XGBoost"]]

fig2, axes2 = plt.subplots(1, 3, figsize=(15, 5))
fig2.suptitle("Model Performance Comparison", fontsize=14, fontweight="bold")

for ax2, metric in zip(axes2, ["MAE", "RMSE", "MAPE"]):
    bars = ax2.bar(metrics_df.index, metrics_df[metric],
                   color=bar_colors, edgecolor="white", lw=0.8, width=0.5)
    ax2.set_title(metric, fontsize=12)
    ax2.set_ylabel(f"{metric} ({'%' if metric == 'MAPE' else 'kW'})")
    fmt = "%.4f" if metric != "MAPE" else "%.2f%%"
    ax2.bar_label(bars, fmt=fmt, padding=3, fontsize=9)
    ax2.grid(axis="y", alpha=0.3)
    ax2.set_ylim(0, metrics_df[metric].max() * 1.30)
    # Highlight best (lowest) bar
    best_idx = metrics_df[metric].values.argmin()
    bars[best_idx].set_edgecolor("gold")
    bars[best_idx].set_linewidth(2.5)

plt.tight_layout()
show_or_save("metrics_comparison.png")

# CELL 13 – Plot 3: XGBoost feature importance
imp_df = (
    pd.Series(xgb_model.feature_importances_, index=feature_cols)
    .sort_values(ascending=False)
    .head(15)
)

fig3, ax3 = plt.subplots(figsize=(11, 6))
imp_df[::-1].plot(kind="barh", ax=ax3, color=COLORS["XGBoost"], edgecolor="white")
ax3.set_title("XGBoost – Top 15 Feature Importances", fontsize=13, fontweight="bold")
ax3.set_xlabel("Importance score")
ax3.grid(axis="x", alpha=0.3)

# Annotate values
for i, v in enumerate(imp_df[::-1].values):
    ax3.text(v + 0.0005, i, f"{v:.4f}", va="center", fontsize=8)

plt.tight_layout()
show_or_save("xgboost_feature_importance.png")

# CELL 14 – Plot 4: Residuals (error distribution per model)
fig4, axes4 = plt.subplots(1, 3, figsize=(15, 5))
fig4.suptitle("Forecast Residuals (Actual − Predicted)", fontsize=14, fontweight="bold")

residuals = {
    "ARIMA"  : y_test.reindex(common_idx) - arima_pred.reindex(common_idx),
    "Prophet": y_test.reindex(common_idx) - prophet_pred.reindex(common_idx),
    "XGBoost": y_te.reindex(common_idx)   - xgb_pred.reindex(common_idx),
}

for ax4, (name, res) in zip(axes4, residuals.items()):
    res = res.dropna()
    ax4.hist(res, bins=40, color=COLORS[name], edgecolor="white", alpha=0.85)
    ax4.axvline(0, color="black", lw=1.5, ls="--")
    ax4.axvline(res.mean(), color="gold", lw=1.5, ls="-", label=f"Mean={res.mean():.4f}")
    ax4.set_title(name, fontsize=12)
    ax4.set_xlabel("Residual (kW)")
    ax4.set_ylabel("Frequency")
    ax4.legend(fontsize=9)
    ax4.grid(alpha=0.3)

plt.tight_layout()
show_or_save("residuals_distribution.png")


# CELL 15 – Summary table
print("\n" + "=" * 58)
print("              FINAL METRICS SUMMARY")
print("=" * 58)
print(metrics_df.to_string(float_format="{:.4f}".format))
best = metrics_df["RMSE"].idxmin()
print(f"\n🏆  Best model by RMSE: {best}")
print("=" * 58)
print("\n📊  4 charts rendered inline above  +  saved as PNG files.")